#ifndef _LOCKPICK_INCLUDE_GRAPH_FUNCTIONS_SHA256_H
#define _LOCKPICK_INCLUDE_GRAPH_FUNCTIONS_SHA256_H

#include <lockpick/graph/graph.h>

#define LPG_SHA256_PADDED_INPUT_CHUNCK_SIZE 512
#define LPG_SHA256_OUTPUT_SIZE 512

#define LPG_SHA256_UPPER_BOUND_NODES_PER_ITER 150000


lpg_graph_t *lpg_sha256_create_graph();


#endif // _LOCKPICK_INCLUDE_GRAPH_FUNCTIONS_SHA256_H